### ISSUE TITLE
.NET Docs are Not Getting Published (Hidden Folder Issue)?

### ISSUE THREAD

**Issue by joshuatz** [nabeelvalley/docs#7]
Hello Nabeel!

This is an *awesome* collection of notes, and your personal website that incorporates them is very slick as well! I have a very similar setup for note taking and publishing via Gatsby / Netlify, and I'm really impressed by how you put this together.

---

I happened to notice though, that all your `.NET` docs are not actually getting *"published"* to the live Netlify site. If I click any link in the `.NET` section on nabeelvalley.netlify.app/docs, it leads to a 404, such as [.NET/integration-service/](https://nabeelvalley.netlify.app/docs/.NET/integration-service/).

I tried to do some digging to see if I could provide you with some tips. I can't say anything conclusively, but I have a hunch this is a UNIX issue with Netlify caused by your folder being named `.NET`, not something with Gatsby or your code. Factors that point this way:
 - On UNIX, a folder starting with a period is pretty special, and often ignored by CLI commands
     - https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory
     - https://unix.stackexchange.com/questions/21778/whats-so-special-about-directories-whose-names-begin-with-a-dot
 - I was not able to replicate this locally on Windows;  `gatsby-source-filesystem` had no problem recursing within a `.___` folder
 - Some quick Google searches didn't bring up a huge amount of relative results for issues with Gatsby or your source plugins

This is probably the most relevant link I could find, and it points to an issue with Netlify: https://community.netlify.com/t/hidden-files-removed-in-zip-deploy/8997

---

The easy fix would probably be to just rename your `.NET` folder to `NET` or `dot-NET` (coincidentally, [that is what I did](https://cheatsheets.joshuatz.com/cheatsheets/dotnet/)). Or, use the redirect workaround in the above link. I'm curious to know if you find anything else out about this!

**Comment by nabeelvalley** [comment]
Hey @joshuatz thanks so much for taking a look and the feedback. Really good to know that it was worth the effort

I actually noticed the issue (very soon after you did coincidentally) with and it looked like the Netlify host server ignores directories with a `.` at the start so far as I can recall and fixed it in this commit c57496fd07eceb8e383621255051c896350bceab

Thanks a ton for the feedback though!
